import os,sys,unittest
ROOT=os.path.dirname(os.path.dirname(__file__));sys.path.insert(0,os.path.join(ROOT,'tools','arena'))
from frontier27_runtime import *

class T(unittest.TestCase):
 def test_00_manifest(self):self.assertEqual((len(FRONTIER_27),len(set(FRONTIER_27))),(27,27))
 def test_01(self):self.assertFalse(HardFalseSecurityGate.admit(source_audited=True,runtime_hard_false=False,remote_code_widening=False))
 def test_02(self):i=HybridIndexBridge(2);i.add('a','alpha beta',(1,2,3));self.assertTrue(i.candidates('alpha beta',64))
 def test_03(self):r=ExportReceipt.build({'x':1},['a'],'g');self.assertTrue(r.reusable(['a'],'g'));self.assertFalse(r.reusable(['b'],'g'))
 def test_04(self):g=TypedGraphEdges();g.add(TypedEdge('a','r','b','p',1));self.assertEqual(g.lookup('a','r')[0].target,'b')
 def test_05(self):self.assertEqual(NativeRouterAuthority.execute([1],[9]),(1,))
 def test_06(self):self.assertEqual(RouterPreservingPrefetch.plan([1],[1,9],[1]),(1,))
 def test_07(self):self.assertEqual(PageCacheStateGate.classify(None),'CALIBRATION_REQUIRED')
 def test_08(self):self.assertTrue(VersionRangeGate.admit('5.1','5','6'));self.assertFalse(VersionRangeGate.admit(None,'5','6'))
 def test_09(self):r=SnapshotRing(2);[r.append(i,i) for i in range(4)];self.assertEqual(len(r),2)
 def test_10(self):c=HotColdCache({'a':1},1);c.get('a');c.get('a');self.assertEqual((c.hits,c.misses),(1,1))
 def test_11(self):t=[StorageTier('s',100,10,1),StorageTier('f',100,20,2)];self.assertEqual(StorageTierPlacement.choose(t,10,1).name,'f')
 def test_12(self):l=StateHandleLease('r','o',1,10);self.assertTrue(l.valid('o',1,9));l.close();self.assertFalse(l.valid('o',1,9))
 def test_13(self):self.assertEqual(WindowAwareBudget.bytes(100,.5,1000),50)
 def test_14(self):self.assertTrue(PrefetchWasteGuard.admit(20,10));self.assertFalse(PrefetchWasteGuard.admit(10,20))
 def test_15(self):t=StorageTier('x',10**9,1e9,2);self.assertTrue(TierEnergyAdmission.admit(t,10**8,.3));self.assertFalse(TierEnergyAdmission.admit(t,10**8,.1))
 def test_16(self):self.assertEqual(UsefulByteAccounting(1,2,3).total,6)
 def test_17(self):c=ExpertResidencyLRU(2);self.assertFalse(c.access(1));self.assertTrue(c.access(1));c.access(2);c.access(3);self.assertFalse(c.resident(1))
 def test_18(self):s=PLEExpertSeparation(1,1);s.access('expert',1);s.access('ple',1);self.assertTrue(s.experts.resident(1));self.assertIn(1,s.ple)
 def test_19(self):e=IdentityEnvelope('m','r','s','h','g');self.assertTrue(P0IdentityGate.admit(e,e));self.assertFalse(P0IdentityGate.admit(e,None))
 def test_20(self):a=PerformanceEnvelope('g','warm',60,2000);b=PerformanceEnvelope('g','warm',61,2020);c=PerformanceEnvelope('g','cold',61,2020);self.assertTrue(MatchedEnvelopeGate.comparable(a,b));self.assertFalse(MatchedEnvelopeGate.comparable(a,c))
 def test_21(self):a=ComponentContract('a','1',frozenset({'x'}),frozenset(),frozenset({'r','w'}));b=ComponentContract('b','1',frozenset(),frozenset({'x'}),frozenset({'r'}));o=CompositionMembrane.compose(a,b,{'x'});self.assertEqual((o['interface'],o['authority']),(('x',),('r',)))
 def test_22(self):c=CollisionBucket();c.put((1,2,3),'a',1);c.put((1,2,3),'b',2);self.assertEqual(c.identities((1,2,3)),('a','b'))
 def test_23(self):self.assertFalse(HardGatePin.admit({'x':False},999));self.assertTrue(HardGatePin.admit({'x':True},0))
 def test_24(self):m=CapabilityManifest(frozenset({'read'}));self.assertTrue(m.allows(['read']));self.assertFalse(m.allows(['write']))
 def test_25(self):a=RetrievalReceipt.build('q',['a'],'g');b=RetrievalReceipt.build('q',['a'],'g');self.assertEqual(a.receipt_digest,b.receipt_digest)
 def test_26(self):c=CurrentnessInvalidator();c.bind('n1',['d1']);c.bind('n2',['d2']);self.assertEqual(c.invalidate(['d1']),{'n1'});self.assertTrue(c.current('n2'))
 def test_27(self):h=HDCSemanticKey();x=h.encode('expert cache');self.assertEqual(h.distance(x,x),0)
 def test_28_security_campaign(self):r=security_campaign(1000);self.assertEqual(r['before_false_admits'],r['after_blocked'])

if __name__=='__main__':unittest.main()
