import unittest
from dataclasses import replace
from hashlib import sha256
from tools.awj032.training_o1_reference.training_admission import *
from tools.awj032.training_r1_resolver_reference.training_admission_resolver import AdmissionSemantic,OwnerResolver
from tools.awj032.training_o2_transition_reference.transition_envelope import *
R=lambda s:sha256(s.encode()).hexdigest()
def setup_chain():
    sv=SourceAuditVerifier({'s':b'src'},'s',2);src=sv._issue_exact(observed_at=1);ts=('l.q_proj','l.v_proj');ks=tuple(sorted(derived_expected_adapter_keys(ts)));vv={k:k.encode() for k in ks};m=AdapterManifest(R('b'),R('c'),R('t'),R('run'),AIRLLM_COMMIT,'qwen3_8_dense','AirLLMLoRA',ts,8,16,False,ks,tuple(h_bytes(vv[k]) for k in ks));a=admit(source_verifier=sv,source=src,manifest=m,observed_base_checkpoint_root=m.base_checkpoint_root,observed_config_root=m.base_config_root,observed_tokenizer_root=m.tokenizer_root,observed_runtime_root=m.runtime_root,observed_target_paths=set(ts),provided_adapter_values=vv,observed_at=2);s=AdmissionSemantic(a.admission_root,a.source_root,a.adapter_root,a.runtime_root,a.target_topology_root,a.base_checkpoint_root,a.base_config_root,a.tokenizer_root,a.adapter_values_root,AIRLLM_COMMIT,a.model_family,a.trainer_class);o=OwnerResolver({'o':b'owner'},'o',3);r=o.issue(s,o1_admission=a,source_verifier=sv,now=10,ttl=30);core=AdapterCore(a.adapter_root,a.base_checkpoint_root,a.adapter_values_root,a.base_config_root,a.tokenizer_root,a.source_root,AIRLLM_COMMIT,a.model_family,a.trainer_class,a.target_topology_root);intent=TransitionIntent(a.adapter_root,R('basecore'),R('from'),core.identity_root,a.runtime_root,R('cache'),'dep');p=o.issue_transition_permit(r,transition_root=intent.intent_root,transition_subject_root=core.identity_root,deployment_generation='dep',now=12,ttl=20,observed_source_root=a.source_root,observed_adapter_root=a.adapter_root,observed_runtime_root=a.runtime_root,observed_target_topology_root=a.target_topology_root);env=TransitionEnvelope(intent,p.permit_root);tr=PhysicalTraceAuthority({'p':b'provider'},'p',4);return sv,m,a,s,o,r,core,intent,p,env,tr
class T(unittest.TestCase):
    def setUp(self): self.sv,self.m,self.a,self.s,self.o,self.r,self.core,self.intent,self.p,self.env,self.tr=setup_chain()
    def pair(self,ok=True):
        c=dict(command_id='c',attempt_id='a',idempotency_key='i',source_envelope_digest=self.env.source_envelope_digest,transition_root=self.env.transition_root,admission_permit_root=self.env.admission_permit_root,adapter_core_root=self.core.identity_root,runtime_root=self.intent.inference_runtime_root);return self.tr.issue_ack(AckPayload(**c,ordinal=1)),self.tr.issue_result(ResultPayload(**c,ordinal=2,provider_success=ok))
    def verify(self,core=None,**kw):
        a,r=self.pair();d=dict(core=core or self.core,env=self.env,permit=self.p,admission_resolver=self.o,trace_authority=self.tr,ack=a,result=r,independently_recomputed_source_digest=self.env.source_envelope_digest,now=13,observed_source_root=self.a.source_root,observed_target_topology_root=self.a.target_topology_root);d.update(kw);return verify_transition(**d)
    def test_valid(self): self.assertEqual(self.verify(),'ADMIT_D0_PROOF_CARRYING_TRANSITION')
    def test_empty_trace_key(self):
        with self.assertRaises(ValueError): PhysicalTraceAuthority({'p':b''},'p',1)
    def test_source_binding(self): self.assertEqual(self.verify(core=replace(self.core,source_root=R('other'))),'HOLD_ADAPTER_CORE_MISMATCH')
    def test_source_binding_with_rebound_env(self):
        c=replace(self.core,source_root=R('other'));i=replace(self.intent,to_adapter_root=c.identity_root);p=self.o.issue_transition_permit(self.r,transition_root=i.intent_root,transition_subject_root=c.identity_root,deployment_generation='dep',now=12,ttl=20,observed_source_root=self.a.source_root,observed_adapter_root=self.a.adapter_root,observed_runtime_root=self.a.runtime_root,observed_target_topology_root=self.a.target_topology_root);e=TransitionEnvelope(i,p.permit_root);common=dict(command_id='c',attempt_id='a',idempotency_key='i',source_envelope_digest=e.source_envelope_digest,transition_root=e.transition_root,admission_permit_root=e.admission_permit_root,adapter_core_root=c.identity_root,runtime_root=i.inference_runtime_root);aa=self.tr.issue_ack(AckPayload(**common,ordinal=1));rr=self.tr.issue_result(ResultPayload(**common,ordinal=2,provider_success=True));self.assertEqual(verify_transition(core=c,env=e,permit=p,admission_resolver=self.o,trace_authority=self.tr,ack=aa,result=rr,independently_recomputed_source_digest=e.source_envelope_digest,now=13,observed_source_root=self.a.source_root,observed_target_topology_root=self.a.target_topology_root),'HOLD_CORE_SOURCE_BINDING')
    def test_topology_binding_rebound(self):
        c=replace(self.core,target_topology_root=R('other'));i=replace(self.intent,to_adapter_root=c.identity_root);p=self.o.issue_transition_permit(self.r,transition_root=i.intent_root,transition_subject_root=c.identity_root,deployment_generation='dep',now=12,ttl=20,observed_source_root=self.a.source_root,observed_adapter_root=self.a.adapter_root,observed_runtime_root=self.a.runtime_root,observed_target_topology_root=self.a.target_topology_root);e=TransitionEnvelope(i,p.permit_root);common=dict(command_id='c',attempt_id='a',idempotency_key='i',source_envelope_digest=e.source_envelope_digest,transition_root=e.transition_root,admission_permit_root=e.admission_permit_root,adapter_core_root=c.identity_root,runtime_root=i.inference_runtime_root);aa=self.tr.issue_ack(AckPayload(**common,ordinal=1));rr=self.tr.issue_result(ResultPayload(**common,ordinal=2,provider_success=True));self.assertEqual(verify_transition(core=c,env=e,permit=p,admission_resolver=self.o,trace_authority=self.tr,ack=aa,result=rr,independently_recomputed_source_digest=e.source_envelope_digest,now=13,observed_source_root=self.a.source_root,observed_target_topology_root=self.a.target_topology_root),'HOLD_CORE_TARGET_TOPOLOGY_BINDING')
    def test_preimage_binding(self):
        c=replace(self.core,base_checkpoint_root=R('other'));i=replace(self.intent,to_adapter_root=c.identity_root);p=self.o.issue_transition_permit(self.r,transition_root=i.intent_root,transition_subject_root=c.identity_root,deployment_generation='dep',now=12,ttl=20,observed_source_root=self.a.source_root,observed_adapter_root=self.a.adapter_root,observed_runtime_root=self.a.runtime_root,observed_target_topology_root=self.a.target_topology_root);e=TransitionEnvelope(i,p.permit_root);cmm=dict(command_id='c',attempt_id='a',idempotency_key='i',source_envelope_digest=e.source_envelope_digest,transition_root=e.transition_root,admission_permit_root=e.admission_permit_root,adapter_core_root=c.identity_root,runtime_root=i.inference_runtime_root);aa=self.tr.issue_ack(AckPayload(**cmm,ordinal=1));rr=self.tr.issue_result(ResultPayload(**cmm,ordinal=2,provider_success=True));self.assertEqual(verify_transition(core=c,env=e,permit=p,admission_resolver=self.o,trace_authority=self.tr,ack=aa,result=rr,independently_recomputed_source_digest=e.source_envelope_digest,now=13,observed_source_root=self.a.source_root,observed_target_topology_root=self.a.target_topology_root),'HOLD_ADAPTER_CORE_PREIMAGE_BINDING')
    def test_bad_sig(self):
        a,r=self.pair();self.assertEqual(self.verify(ack=replace(a,mac=R('bad')),result=r),'HOLD_ACK_SIGNATURE')
    def test_provider_false(self):
        a,r=self.pair(False);self.assertEqual(self.verify(ack=a,result=r),'HOLD_PROVIDER_RESULT')
    def test_missing_result_bool(self):
        with self.assertRaises(TypeError): ResultPayload('c','a','i',R('s'),R('t'),R('p'),R('a'),R('r'),1)
    def test_empty_ids(self):
        with self.assertRaises(ValueError): AckPayload('','a','i',R('s'),R('t'),R('p'),R('a'),R('r'),1)
if __name__=='__main__': unittest.main()
