#!/usr/bin/env python3
"""Exact-input verification for observation-bound WorkCapsule closure receipts.

PR516 removes caller-prepared source/candidate injection by deriving candidate source
witnesses from raw ASTGE currentness evidence and compiling the WorkCapsule candidate
internally before delegating closure to PR512. PR513 independently proves that a
self-digest-consistent closure receipt is weaker than deterministic reproduction from
its pinned closure inputs.

This D0 membrane composes those laws. It reruns PR516 from the exact raw currentness
inputs, previous WorkCapsule binding, O8 re-entry receipt and candidate graph witness,
then requires canonical byte equality with the candidate PR516 receipt. Whenever both
the candidate and independently replayed PR516 consequence contain an inner PR512
closure receipt, the PR513 exact-closure verifier is replayed against the independently
derived candidate binding. A CLOSED-vs-HOLD inner-closure presence mismatch is itself
an exact-input contradiction and is never coerced into closure.

Exact reproduction is not producer authentication, semantic truth, review approval,
mutation authority, execution authority, commit/merge authority, or external effect.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from scripts.aura_workcapsule_observation_bound_closure import (
    compile_observation_bound_reentry_closure,
    verify_observation_bound_reentry_closure,
)
from scripts.aura_workcapsule_reentry_closure_exact_verifier import verify_exact_reentry_closure

VERSION = "AURA_WORKCAPSULE_OBSERVATION_BOUND_EXACT_VERIFIER_V1"
EXACT_OBSERVATION_BOUND_INPUT_MISMATCH = "OBSERVATION_BOUND_RECEIPT_NOT_EXACT_INPUT_REPRODUCTION"
PREVIOUS_BINDING_IDENTITY_MISMATCH = "OBSERVATION_BOUND_PREVIOUS_BINDING_IDENTITY_NOT_EXACT"
REENTRY_RECEIPT_IDENTITY_MISMATCH = "OBSERVATION_BOUND_REENTRY_RECEIPT_IDENTITY_NOT_EXACT"
SOURCE_OBSERVATION_IDENTITY_MISMATCH = "OBSERVATION_BOUND_SOURCE_OBSERVATION_IDENTITY_NOT_EXACT"
DERIVED_CANDIDATE_IDENTITY_MISMATCH = "OBSERVATION_BOUND_DERIVED_CANDIDATE_IDENTITY_NOT_EXACT"
INNER_CLOSURE_PRESENCE_MISMATCH = "OBSERVATION_BOUND_INNER_CLOSURE_PRESENCE_NOT_EXACT"


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def verify_exact_observation_bound_reentry_closure(
    *,
    root: Path,
    codemap: dict[str, Any],
    anchor_manifest: dict[str, Any],
    witness_manifest: dict[str, Any],
    previous_binding: dict[str, Any],
    reentry_receipt: dict[str, Any],
    candidate_graph_witness: dict[str, Any],
    receipt: dict[str, Any],
) -> list[str]:
    """Verify one PR516 receipt as the exact consequence of the pinned raw inputs.

    The public boundary intentionally accepts neither ``candidate_binding`` nor
    ``observed_source_witnesses``. Those values are independently regenerated by
    PR516 from the raw source-currentness owner inputs supplied here.
    """
    violations = [
        f"PR516_{item}" for item in verify_observation_bound_reentry_closure(receipt)
    ]

    expected = compile_observation_bound_reentry_closure(
        root=root,
        codemap=codemap,
        anchor_manifest=anchor_manifest,
        witness_manifest=witness_manifest,
        previous_binding=previous_binding,
        reentry_receipt=reentry_receipt,
        candidate_graph_witness=candidate_graph_witness,
    )

    if receipt.get("previous_binding_identity") != previous_binding.get("binding_identity"):
        violations.append(PREVIOUS_BINDING_IDENTITY_MISMATCH)
    if receipt.get("reentry_receipt_identity") != reentry_receipt.get("receipt_identity"):
        violations.append(REENTRY_RECEIPT_IDENTITY_MISMATCH)
    if receipt.get("source_observation_identity") != expected.get("source_observation_identity"):
        violations.append(SOURCE_OBSERVATION_IDENTITY_MISMATCH)
    if receipt.get("derived_candidate_binding_identity") != expected.get(
        "derived_candidate_binding_identity"
    ):
        violations.append(DERIVED_CANDIDATE_IDENTITY_MISMATCH)

    closure = receipt.get("closure_receipt")
    expected_closure = expected.get("closure_receipt")
    if isinstance(closure, dict) and isinstance(expected_closure, dict):
        inner_violations = verify_exact_reentry_closure(
            previous_binding=previous_binding,
            reentry_receipt=reentry_receipt,
            candidate_binding=expected["derived_candidate_binding"],
            closure_receipt=closure,
        )
        violations.extend(f"PR513_{item}" for item in inner_violations)
    elif isinstance(closure, dict) != isinstance(expected_closure, dict):
        violations.append(INNER_CLOSURE_PRESENCE_MISMATCH)

    if _canonical_bytes(receipt) != _canonical_bytes(expected):
        violations.append(EXACT_OBSERVATION_BOUND_INPUT_MISMATCH)

    return list(dict.fromkeys(violations))


def admit_exact_observation_bound_reentry_closure(
    *,
    root: Path,
    codemap: dict[str, Any],
    anchor_manifest: dict[str, Any],
    witness_manifest: dict[str, Any],
    previous_binding: dict[str, Any],
    reentry_receipt: dict[str, Any],
    candidate_graph_witness: dict[str, Any],
    receipt: dict[str, Any],
) -> dict[str, Any]:
    """Return a narrow exact-reproduction admission or fail closed."""
    violations = verify_exact_observation_bound_reentry_closure(
        root=root,
        codemap=codemap,
        anchor_manifest=anchor_manifest,
        witness_manifest=witness_manifest,
        previous_binding=previous_binding,
        reentry_receipt=reentry_receipt,
        candidate_graph_witness=candidate_graph_witness,
        receipt=receipt,
    )
    if violations:
        raise ValueError(
            "observation-bound closure exact-input verification failed: " + ",".join(violations)
        )

    inner_closure = receipt.get("closure_receipt")
    return {
        "version": VERSION,
        "exact_observation_bound_input_reproduction": True,
        "closure_status": receipt["closure_status"],
        "previous_binding_identity": receipt["previous_binding_identity"],
        "reentry_receipt_identity": receipt["reentry_receipt_identity"],
        "source_observation_identity": receipt["source_observation_identity"],
        "derived_candidate_binding_identity": receipt["derived_candidate_binding_identity"],
        "observation_bound_receipt_identity": receipt["receipt_identity"],
        "inner_closure_exact_reproduction": isinstance(inner_closure, dict),
        "candidate_source_basis_derived_from_raw_currentness_inputs": True,
        "caller_candidate_binding_accepted": False,
        "caller_source_witnesses_accepted": False,
        "producer_identity_authenticated": False,
        "graph_witness_producer_authenticated": False,
        "semantic_truth_minted": False,
        "authority": {
            "review_authorized": False,
            "mutation_authorized": False,
            "execution_authorized": False,
            "commit_authorized": False,
            "merge_authorized": False,
            "promotion_authorized": False,
            "provider_effect_authorized": False,
            "public_effect_authorized": False,
            "human_authority": False,
        },
    }
